# configure Mysql connection

spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3307/petcare?characterEncoing=utf-8
      username: root
      password: fuji

# configure mybatis
mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml
  type-aliases-package: com.psm.petcare.entity

